"""initial schema

Revision ID: 3444b8a393ab
Revises: 
Create Date: 2026-09-11 18:13:07.802688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3444b8a393ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lon', sa.Float(), nullable=False),
    sa.Column('default_zoom', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_regions_boundary', 'regions', ['boundary'], unique=False, postgresql_using='gist')
    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('component', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_landslides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Text(), server_default='reported', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historical_geom', 'historical_landslides', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_historical_landslides_geom', 'historical_landslides', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('infrastructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('osm_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id', name='uq_infrastructure_osm_id')
    )
    op.create_index('idx_infra_geom', 'infrastructure', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_infra_region_cat', 'infrastructure', ['region_id', 'category'], unique=False)
    op.create_index('idx_infrastructure_geom', 'infrastructure', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('slope_deg', sa.Float(), nullable=True),
    sa.Column('soil_class', sa.Text(), nullable=True),
    sa.Column('soil_retention_score', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locations_geom', 'locations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('idx_locations_region', 'locations', ['region_id'], unique=False)
    op.create_table('rainfall_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('source', sa.Text(), server_default='open-meteo', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'obs_date', 'source', name='uq_rainfall_region_date_source')
    )
    op.create_index('idx_rainfall_region_date', 'rainfall_observations', ['region_id', 'obs_date'], unique=False, postgresql_ops={'obs_date': 'DESC'})
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('slope_deg', sa.Float(), nullable=True),
    sa.Column('soil_score', sa.Float(), nullable=True),
    sa.Column('historical_score', sa.Float(), nullable=True),
    sa.Column('sensor_adjustment', sa.Float(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_region_time', 'risk_assessments', ['region_id', 'computed_at'], unique=False)
    op.create_table('sensor_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('baseline_tilt_x', sa.Float(), server_default='0', nullable=True),
    sa.Column('baseline_tilt_y', sa.Float(), server_default='0', nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='offline', nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=False),
    sa.Column('factor_name', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('normalized_value', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('contribution', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_riskfactors_assessment', 'risk_factors', ['risk_assessment_id'], unique=False)
    op.create_table('sensor_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anomaly_type', sa.Text(), nullable=False),
    sa.Column('peak_magnitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomalies_node', 'sensor_anomalies', ['node_id', 'started_at'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('rain_wetness', sa.Float(), nullable=True),
    sa.Column('rain_active', sa.Boolean(), nullable=True),
    sa.Column('tilt_x', sa.Float(), nullable=True),
    sa.Column('tilt_y', sa.Float(), nullable=True),
    sa.Column('tilt_magnitude', sa.Float(), nullable=True),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_readings_node_time', 'sensor_readings', ['node_id', 'recorded_at'], unique=False)
    op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index('idx_readings_node_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index('idx_anomalies_node', table_name='sensor_anomalies')
    op.drop_table('sensor_anomalies')
    op.drop_index('idx_riskfactors_assessment', table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_table('sensor_nodes')
    op.drop_index('idx_risk_region_time', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_table('scenarios')
    op.drop_index('idx_rainfall_region_date', table_name='rainfall_observations', postgresql_ops={'obs_date': 'DESC'})
    op.drop_table('rainfall_observations')
    op.drop_index('idx_locations_region', table_name='locations')
    op.drop_index('idx_locations_geom', table_name='locations', postgresql_using='gist')
    op.drop_table('locations')
    op.drop_index('idx_infrastructure_geom', table_name='infrastructure', postgresql_using='gist')
    op.drop_index('idx_infra_region_cat', table_name='infrastructure')
    op.drop_index('idx_infra_geom', table_name='infrastructure', postgresql_using='gist')
    op.drop_table('infrastructure')
    op.drop_index('idx_historical_landslides_geom', table_name='historical_landslides', postgresql_using='gist')
    op.drop_index('idx_historical_geom', table_name='historical_landslides', postgresql_using='gist')
    op.drop_table('historical_landslides')
    op.drop_table('system_logs')
    op.drop_index('idx_regions_boundary', table_name='regions', postgresql_using='gist')
    op.drop_table('regions')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
