"""persist sensor source mode

Revision ID: 8f2c1a9d4b77
Revises: 3444b8a393ab
"""
from alembic import op
import sqlalchemy as sa

revision = "8f2c1a9d4b77"
down_revision = "3444b8a393ab"
branch_labels = None
depends_on = None

def upgrade():
    op.add_column("sensor_readings", sa.Column("source_mode", sa.Text(), nullable=False, server_default="LIVE"))
    # All readings predating this provenance column were generated by the bundled simulator.
    op.execute("UPDATE sensor_readings SET source_mode='SIMULATED'")

def downgrade():
    op.drop_column("sensor_readings", "source_mode")
